import Header from "@/components/layout/Header";
import { NextIntlClientProvider, hasLocale } from "next-intl";
import { notFound } from "next/navigation";
import { routing } from "@/app/i18n/routing";
import type { Metadata } from "next";
import { Geist, Inter } from "next/font/google";
import "@/app/globals.css";
import Footer from "@/components/layout/Footer";

const geistSans = Geist({
	variable: "--font-geist",
	subsets: ["latin"],
});

const inter = Inter({
	variable: "--font-inter",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const RootLayout = async ({
	children,
	params,
}: Readonly<{
	children: React.ReactNode;
	params: Promise<{ locale: string }>;
}>) => {
	const { locale } = await params;
	if (!hasLocale(routing.locales, locale)) {
		notFound();
	}
	return (
		<>
			<html lang={locale}>
				<body className={`${geistSans.variable} ${inter.variable} antialiased`}>
					<Header />
					<NextIntlClientProvider>{children}</NextIntlClientProvider>
					<Footer />
				</body>
			</html>
		</>
	);
};

export default RootLayout;
